"""add steps_data to recipes

Revision ID: 32adc4af25e2
Revises: 
Create Date: 2026-02-24 10:57:21.136754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32adc4af25e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steps_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('steps_data')

    # ### end Alembic commands ###
